@EmbedderHost=http://localhost:7883

POST {{EmbedderHost}}/v1/embeddings
Content-Type: application/json

{"input":"The quick brown fox jumped over the lazy dog","encoding_format":"float"}

###

POST {{EmbedderHost}}/v1/embeddings
Content-Type: application/json

{"input":["First sentence.","Another sentence."],"encoding_format":"base64"}

###

POST {{EmbedderHost}}/v1/relevances
Content-Type: application/json

{"input":[["Question?","First answer."],["Question?","Second answer."]]}

###