version: '3.4'
name: maize-kb-tools
services:
  embedder:
    image: ${DOCKER_REGISTRY-}embedder
    build:
      context: .
      dockerfile: Embedder/Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface
  # one-off tools below
  embedder-cache:
    scale: 0
    build:
      context: .
      dockerfile: Embedder/Dockerfile
    entrypoint: python3 main.py
    volumes:
      - huggingface:/root/.cache/huggingface
  vimeo-downloader:
    scale: 0
    image: ${DOCKER_REGISTRY-}vimeo-downloader
    build:
      context: .
      dockerfile: VimeoDownloader/Dockerfile
    volumes:
      - ../:/data
  youtube-dl:
    scale: 0
    image: ${DOCKER_REGISTRY-}youtube-dl
    build:
      context: .
      dockerfile: youtube-dl/Dockerfile
    volumes:
      - ../:/data
  transcriber:
    scale: 0
    build:
      context: .
      dockerfile: Transcriber/Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface
      - ../:/data
    entrypoint: /bin/bash -O globstar -c "whisperx --model large-v3 --output_format json --task transcribe --language zh --align_model StevenLimcorn/wav2vec2-xls-r-300m-zh-TW --initial_prompt '弟兄姊妹平安，我們一起來思想。繁體中文，臺灣國語。' --output_dir /data/whisperx /data/source/**/*.{m4a,opus}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  whisperx-json-trimmer:
    scale: 0
    build:
      context: .
      dockerfile: WhisperXJsonTrimmer/Dockerfile
    volumes:
      - ../:/data
  resegmenter:
    scale: 0
    image: ${DOCKER_REGISTRY-}resegmenter
    build:
      context: .
      dockerfile: Resegmenter/Dockerfile
    volumes:
      - ../:/data
  chinese-converter:
    scale: 0
    build:
      context: .
      dockerfile: ChineseConverter/Dockerfile
    volumes:
      - ../:/data
  descriptor:
    scale: 0
    build:
      context: .
      dockerfile: Descriptor/Dockerfile
    env_file:
      - secrets.env
    volumes:
      - ../:/data
  semantic-chunker:
    scale: 0
    image: ${DOCKER_REGISTRY-}semantic-chunker
    build:
      context: .
      dockerfile: SemanticChunker/Dockerfile
    volumes:
      - ../:/data
    environment:
      EMBEDDER_HOST: http://embedder/
  translator:
    image: ${DOCKER_REGISTRY-}translator
    build:
      context: .
      dockerfile: Translator/Dockerfile
    volumes:
      - huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  huggingface:
    external: true
